kind: pipeline
name: default

steps:
  - name: build
    image: node:6-slim
    commands:
      - node -v
      - npm -v
      - npm install --global gitbook-cli
      - gitbook install && gitbook build
